//function GoOrder() {
//    window.location = "Order.aspx";
//    var frm = document.getElementById('mainframe');
//    if (frm) {
//        frm.setAttribute('style', 'display:block;');
//        frm.setAttribute('src', 'Order.aspx');

//    }
//    var div = document.getElementById('maincontentdiv');
//    if (div) {
//        div.setAttribute('style', 'display:none;');
//    }


//}
function SetHelp(type) { ///expands the help window

    var div = window.parent.document.getElementById('helpdiv');
    var td = window.parent.document.getElementById('helptd');
    if (div && td) {
        //div.style.backgroundColor = "white";
        //div.style.width = "300px";
        //div.style.minwidth = "300px";
        //div.style.maxwidth = "300px";
        //td.style.backgroundColor = "white";
        if (td.style.display == 'none' | td.style.display == '') {
            td.style.display = 'block';
        }
        else {
            td.style.display = 'none';
        }
        div.innerHTML = "<H2 class ='helpclose'><a class ='helpclose' href = 'Javascript:CloseHelp()'>Close Window</a>&nbsp&nbsp&nbsp&nbsp<br></h2>";
        div.innerHTML += "<H2 class='help'>Help With This Feature</H2>";
        if (type == 1) {//register
            div.innerHTML += '<br><H2>Watch a video that shows you how to register with the Texas Crop Registry:<H2><br>';
            div.innerHTML += '<iframe width="600" height="500" src="//www.youtube.com/embed/gDcd7nZsri0" frameborder="0" allowfullscreen></iframe>';
            div.innerHTML += "<br><br><H3 class='help'>Use standard YouTube video controls to pause, play, adjust sound and switch between full screen mode</H3><br>";
            var str = "";
            str += "<H3 class='help'>Main Points:</H3><UL class='helplist'><LI>Fill in all the required fields on the registration form.</LI>";
            str += "<LI>The email you provide will be your username for the registry. Check your email inbox for messages from the Texas Crop Registry </LI>";
            str += "<LI>After you have submitted your details, an autogenerated password will be sent to your email address.</LI>";
            str += "<LI>Use the autogenerated password to login to the site for the first time.</LI>";
            str += "<LI>Use the 'change password' link to choose a more memorable password once you have received you autogenerated password.</LI>";
            str += "<LI>If you forget your password, use the 'forgotten password' link to obtain a new autogenerated password.</LI></UL>";
            
            div.innerHTML += str;
            //div.innerHTML += "<br><br><H3 class='help'>For more help, please contact Agrilife Extension's Agricultural and Environmental Safety team:<br><br>Denise King: (979) 845-3849 <br><br>If you would like to provide feedback, please send an email to:<br><br> TexasCropRegistry@gmail.com</H3>";
        }
        else if (type == 3) { ///applicatorr dashboard
            div.innerHTML += '<br><H2>Watch a video that shows you how to add, manage and edit Application Areas:<H2><br>';
            div.innerHTML += '<iframe width="600" height="500" src="//www.youtube.com/embed/_hJTVGEieLY" frameborder="0" allowfullscreen></iframe>';
            div.innerHTML += "<br><br><H3 class='help'>Use standard YouTube video controls to pause, play, adjust sound and switch between full screen mode</H3><br>";
            var str = "";
            str += "<H3 class='help'>Main Points:</H3><UL class='helplist'><LI>Add a new apppplication area  using the 'Add New Area' button. Your application areas are confidential and can only be viewed by you.</LI>";
            str += "<LI>Set your notification preferences to determine whether you would like to be notified as new crop locations are added to the registry.</LI>";
            str += "<LI>You can edit or delete locations at any time.</LI>";
           str += "<LI>Use the inbuilt tools to look for all potentially conflicting crop locations</LI>";
           str += "<LI>Use the page numbers if you have more than 10 application areas defined.</LI>";
          
           div.innerHTML += str;
           //div.innerHTML += "<br><br><H3 class='help'>For more help, please contact Agrilife Extension's Agricultural and Environmental Safety team:<br><br>Denise King: (979) 845-3849 <br><br>If you would like to provide feedback, please send an email to:<br><br>  TexasCropRegistry@gmail.com</H3>";
        }
        else if (type == 2) { ///producer dashboard
            div.innerHTML += '<br><H2>Watch a video that shows you how to add, manage and edit your crop locations:<H2><br>';
            div.innerHTML += '<iframe width="600" height="500" src="//www.youtube.com/embed/pWifhIbYuPo" frameborder="0" allowfullscreen></iframe>';
            div.innerHTML += "<br><br><H3 class='help'>Use standard YouTube video controls to pause, play, adjust sound and switch between full screen mode</H3><br>";
            var str = "";
            str += "<H3 class='help'>Main Points:</H3><UL class='helplist'><LI>Add a new location using the 'Add New Crop Location' link.</LI>";
            str += "<LI>You can edit or delete locations at any time.</LI>";
            str += "<LI>Click on a crop to zoom in to the area on the map.</LI>";
            str += "<LI>Use the page numbers if you have more than 10 crop locations defined.</LI>";
            str += "<LI>Your crops will expire on 1st of January every year.</LI></UL>";
            div.innerHTML += str;
            
        }
        else if (type == 4) {
            
        }
        div.innerHTML += "<br><br><H3 class='help'>For more help, please contact Agrilife Extension's Agricultural and Environmental Safety team:<br><br>Denise King: (979) 845-3849 <br><br>If you would like to provide feedback, please send an email to:<br><br>  <a class='helpclose' href='mailto:TexasCropRegistry@gmail.com?Subject=Texas Crop Registry Feedback' target='_top'>TexasCropRegistry@gmail.com</a></H3>";
        div.scrollIntoView();
        //window.location.hash = "#helpdiv";
    }

}

function CloseHelp() {

    var div = window.parent.document.getElementById('helpdiv');
    var td = window.parent.document.getElementById('helptd');
    if (div && td) {
        td.style.display = 'none';
        div.innerHTML = "";
    }
}

function GoHome() 
{
    
    CloseHelp();
    var el = document.getElementById('contentIframe');
    if (el) {
        //        alert(user);
        el.setAttribute('src', 'Home.aspx');
    }
    else 
    {
        window.parent.location.reload();
    }
    
//     window.location = "Default.aspx";
}
function GoBackground() {

    CloseHelp();
    var el = document.getElementById('contentIframe');
    if (el) {
        //        alert(user);
        el.setAttribute('src', 'Background.aspx');
    }
    else {
        window.parent.location.reload();
    }

    //     window.location = "Default.aspx";
}
function GoProducer() 
{
    CloseHelp();
    var el = document.getElementById('contentIframe');
    if (el) {
        if (user != null) 
        {
            el.setAttribute('src', 'Producer.aspx');
        }
        else {
            el.setAttribute('src', 'Account.aspx');
        }
    }
    else {
        if (user != null) 
        {
            window.location = "Producer.aspx";
        }
        else {
            window.location = "Account.aspx";
        }
    }

    //        window.location = "Home.aspx";
}
//function GoTrapData() {
//    window.location = "TrapData.aspx";
//}
function GoApplicator() {
    CloseHelp();
    var el = document.getElementById('contentIframe');
    if (el) 
    {
        if (user != null) {
            el.setAttribute('src', 'Applicator.aspx');
        }
        else {
            el.setAttribute('src', 'Account.aspx');
        }
    }
    else {
        if (user != null) {
            window.location = "Applicator.aspx";
        }
        else {
            window.location = "Account.aspx";
        }
    }

    //        window.location = "Home.aspx";
}
function GoAccount(type) 
{
    CloseHelp();
    var el = document.getElementById('contentIframe');
    if (el) {
        if (type) {
            el.setAttribute('src', 'Account.aspx?type='+ type);
        }
        else {

            el.setAttribute('src', 'Account.aspx');
        }
    }
//    window.location = 'Account.aspx';
}
function GoMap() {
    CloseHelp();
    var el = document.getElementById('contentIframe');
    if (el) 
    {
        el.setAttribute('src', 'PublicMap.aspx');
    }

    //        window.location = "Home.aspx";
}

function GoFAQ() {
    CloseHelp();
    var el = document.getElementById('contentIframe');
    if (el) {
        el.setAttribute('src', 'FAQ.aspx');
    }

    //        window.location = "Home.aspx";
}

function GoNewArea(qrystr) {

    var el = document.getElementById('contentIframe');
//    alert(frame);
    if (el) {
        if (user != null) {
            if (user.preferences == "none") {
                alert('Please save your preferences before Adding a new area!');
            }
            else { el.setAttribute('src', 'NewArea.aspx?' + qrystr); }
        }
        else {
            el.setAttribute('src', 'Account.aspx');
        }
    }
    else {
        if (user != null) {
            if (user.preferences == "none") {
                alert('Please save your preferences before Adding a new area!');
            }
            else { window.location = "NewArea.aspx?" + qrystr; }
        }
        else {
            window.location = "Account.aspx";
        }
    }
}
function GoNewCrop(qrystr) {

    var el = document.getElementById('contentIframe');
    //    alert(frame);
    if (el) {
        if (user != null) {
            el.setAttribute('src', 'NewCrop.aspx?' + qrystr);
        }
        else {
            el.setAttribute('src', 'Account.aspx');
        }
    }
    else {
        if (user != null) {
           window.location = "NewCrop.aspx?" + qrystr;
        }
        else {
            window.location = "Account.aspx";
        }
    }
}

function getElement(aID) {
    return (document.getElementById) ? document.getElementById(aID) : document.all[aID];
}