function CreateOptions(selectid, selecttype) {
    var select = document.getElementById(selectid);
    if (select) {
        var options = new Array();
        if (selectid == "counties" || selectid == "acounties" || selectid == "county")
        {
            options.push("--Select county--");
            if (selecttype == "view") {
                options.push("All Counties");
            }
            options.push("Anderson");
            options.push("Andrews");
            options.push("Angelina");
            options.push("Aransas");
            options.push("Archer");
            options.push("Armstrong");
            options.push("Atascosa");
            options.push("Austin");
            options.push("Bailey");
            options.push("Bandera");
            options.push("Bastrop");
            options.push("Baylor");
            options.push("Bee");
            options.push("Bell");
            options.push("Bexar");
            options.push("Blanco");
            options.push("Borden");
            options.push("Bosque");
            options.push("Bowie");
            options.push("Brazoria");
            options.push("Brazos");
            options.push("Brewster");
            options.push("Briscoe");
            options.push("Brooks");
            options.push("Brown");
            options.push("Burleson");
            options.push("Burnet");
            options.push("Caldwell");
            options.push("Calhoun");
            options.push("Callahan");
            options.push("Cameron");
            options.push("Camp");
            options.push("Carson");
            options.push("Cass");
            options.push("Castro");
            options.push("Chambers");
            options.push("Cherokee");
            options.push("Childress");
            options.push("Clay");
            options.push("Cochran");
            options.push("Coke");
            options.push("Coleman");
            options.push("Collin");
            options.push("Collingsworth");
            options.push("Colorado");
            options.push("Comal");
            options.push("Comanche");
            options.push("Concho");
            options.push("Cooke");
            options.push("Coryell");
            options.push("Cottle");
            options.push("Crane");
            options.push("Crockett");
            options.push("Crosby");
            options.push("Culberson");
            options.push("Dallam");
            options.push("Dallas");
            options.push("Dawson");
            options.push("Deaf Smith");
            options.push("Delta");
            options.push("Denton");
            options.push("DeWitt");
            options.push("Dickens");
            options.push("Dimmit");
            options.push("Donley");
            options.push("Duval");
            options.push("Eastland");
            options.push("Ector");
            options.push("Edwards");
            options.push("El Paso");
            options.push("Ellis");
            options.push("Erath");
            options.push("Falls");
            options.push("Fannin");
            options.push("Fayette");
            options.push("Fisher");
            options.push("Floyd");
            options.push("Foard");
            options.push("Fort Bend");
            options.push("Franklin");
            options.push("Freestone");
            options.push("Frio");
            options.push("Gaines");
            options.push("Galveston");
            options.push("Garza");
            options.push("Gillespie");
            options.push("Glasscock");
            options.push("Goliad");
            options.push("Gonzales");
            options.push("Gray");
            options.push("Grayson");
            options.push("Gregg");
            options.push("Grimes");
            options.push("Guadalupe");
            options.push("Hale");
            options.push("Hall");
            options.push("Hamilton");
            options.push("Hansford");
            options.push("Hardeman");
            options.push("Hardin");
            options.push("Harris");
            options.push("Harrison");
            options.push("Hartley");
            options.push("Haskell");
            options.push("Hays");
            options.push("Hemphill");
            options.push("Henderson");
            options.push("Hidalgo");
            options.push("Hill");
            options.push("Hockley");
            options.push("Hood");
            options.push("Hopkins");
            options.push("Houston");
            options.push("Howard");
            options.push("Hudspeth");
            options.push("Hunt");
            options.push("Hutchinson");
            options.push("Irion");
            options.push("Jack");
            options.push("Jackson");
            options.push("Jasper");
            options.push("Jeff Davis");
            options.push("Jefferson");
            options.push("Jim Hogg");
            options.push("Jim Wells");
            options.push("Johnson");
            options.push("Jones");
            options.push("Karnes");
            options.push("Kaufman");
            options.push("Kendall");
            options.push("Kenedy");
            options.push("Kent");
            options.push("Kerr");
            options.push("Kimble");
            options.push("King");
            options.push("Kinney");
            options.push("Kleberg");
            options.push("Knox");
            options.push("La Salle");
            options.push("Lamar");
            options.push("Lamb");
            options.push("Lampasas");
            options.push("Lavaca");
            options.push("Lee");
            options.push("Leon");
            options.push("Liberty");
            options.push("Limestone");
            options.push("Lipscomb");
            options.push("Live Oak");
            options.push("Llano");
            options.push("Loving");
            options.push("Lubbock");
            options.push("Lynn");
            options.push("Madison");
            options.push("Marion");
            options.push("Martin");
            options.push("Mason");
            options.push("Matagorda");
            options.push("Maverick");
            options.push("McCulloch");
            options.push("McLennan");
            options.push("McMullen");
            options.push("Medina");
            options.push("Menard");
            options.push("Midland");
            options.push("Milam");
            options.push("Mills");
            options.push("Mitchell");
            options.push("Montague");
            options.push("Montgomery");
            options.push("Moore");
            options.push("Morris");
            options.push("Motley");
            options.push("Nacogdoches");
            options.push("Navarro");
            options.push("Newton");
            options.push("Nolan");
            options.push("Nueces");
            options.push("Ochiltree");
            options.push("Oldham");
            options.push("Orange");
            options.push("Palo Pinto");
            options.push("Panola");
            options.push("Parker");
            options.push("Parmer");
            options.push("Pecos");
            options.push("Polk");
            options.push("Potter");
            options.push("Presidio");
            options.push("Rains");
            options.push("Randall");
            options.push("Reagan");
            options.push("Real");
            options.push("Red River");
            options.push("Reeves");
            options.push("Refugio");
            options.push("Roberts");
            options.push("Robertson");
            options.push("Rockwall");
            options.push("Runnels");
            options.push("Rusk");
            options.push("Sabine");
            options.push("San Augustine");
            options.push("San Jacinto");
            options.push("San Patricio");
            options.push("San Saba");
            options.push("Schleicher");
            options.push("Scurry");
            options.push("Shackelford");
            options.push("Shelby");
            options.push("Sherman");
            options.push("Smith");
            options.push("Somervell");
            options.push("Starr");
            options.push("Stephens");
            options.push("Sterling");
            options.push("Stonewall");
            options.push("Sutton");
            options.push("Swisher");
            options.push("Tarrant");
            options.push("Taylor");
            options.push("Terrell");
            options.push("Terry");
            options.push("Throckmorton");
            options.push("Titus");
            options.push("Tom Green");
            options.push("Travis");
            options.push("Trinity");
            options.push("Tyler");
            options.push("Upshur");
            options.push("Upton");
            options.push("Uvalde");
            options.push("Val Verde");
            options.push("Van Zandt");
            options.push("Victoria");
            options.push("Walker");
            options.push("Waller");
            options.push("Ward");
            options.push("Washington");
            options.push("Webb");
            options.push("Wharton");
            options.push("Wheeler");
            options.push("Wichita");
            options.push("Wilbarger");
            options.push("Willacy");
            options.push("Williamson");
            options.push("Wilson");
            options.push("Winkler");
            options.push("Wise");
            options.push("Wood");
            options.push("Yoakum");
            options.push("Young");
            options.push("Zapata");
            options.push("Zavala");
        }
        if (options.length > 0)
        {
            select.innerHTML = "";
            // --Select-- option
            var option = document.createElement('option');
            option.value = "";
            option.innerHTML = options[0];
            select.appendChild(option);

            for (var x = 1; x < options.length; x++) {
                var option = document.createElement('option');
                var alloption = options[x].match(/All/g);
                if (alloption) { option.value = "All"; }
                else { option.value = options[x]; }
                option.innerHTML = options[x];
                select.appendChild(option);
            }
        }
        select.setAttribute('style', 'visibility: visible; display: block;');
    }
}
